### ISSUE TITLE
Add  new  settings in `website` section

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-types-lib#24]
Depends on: https://github.com/torrust/torrust-index/issues/730

Relates to: 
- https://github.com/torrust/torrust-index/issues/730
- https://github.com/torrust/torrust-index-gui/issues/617

We to update settings type to follow changes in the Index.

```toml
[website]
name = "Torrust"

[website.demo]
warning = "..."

[website.terms]

[website.terms.upload]
content_upload_agreement = "..."

[website.terms.page]
title = "Usage Policies and Content Restrictions"
content = "..."
```
